import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Form from "@/components/Form";
import { useState } from "react";
import { uid } from "uid";

const inter = Inter({ subsets: ["latin"] });

function handleSubmit(event) {
  event.preventDefault();
  const formData = new FormData(event.target);
  const data = Object.fromEntries(formData);

  console.log(data.activity);
  console.log(data.isGoodWeatherActivity);

  event.target.reset();
}

export default function Home() {
  const [activity, setActivity] = useState([]);

  function handleAddActivity(newActivity) {
    setActivity([...activity, { ...newActivity, id: uid() }]);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        {activity.map((element) => {
          return <li key={element.id}>{element.name}</li>;
        })}
      </ul>
      <Form onSubmit={handleSubmit} onAddActivity={handleAddActivity} />
    </>
  );
}
