import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Form from "@/components/Form";
import { useState } from "react";
import { uid } from "uid";
import useLocalStorageState from "use-local-storage-state";

const inter = Inter({ subsets: ["latin"] });

const isGoodWeather = true;

export default function Home() {
  const [activity, setActivity] = useLocalStorageState("activities", {
    defaultValue: [],
  });

  function handleAddActivity(newActivity) {
    setActivity([...activity, { ...newActivity, id: uid() }]);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>The Activity App</h1>
        <ul className="activities-list">
          {activity.map((element) => {
            return (
              <li className="activities" key={element.id}>
                {element.name}
              </li>
            );
          })}
        </ul>
        <Form onAddActivity={handleAddActivity} />
      </main>
    </>
  );
}
